### ISSUE TITLE
Account creation and initial security setup

### ISSUE THREAD

**Issue by HobbesMD** [rbcministries/gvsu-aci-recommendation-engine#2]

**Comment by lobb00** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GVSU-ACI-Project-61f43b9f94097000171537d5/issues/rbcministries/gvsu-aci-recommendation-engine/2?planning-poker) with ZenHub @elinderm @HobbesMD @jacobwrestlesangels
